                                        #PROJECT
                                        
	# data used - 
		#- customer_details
                #- sales_details
		#- product_details
                #- region
                
/*Q1
Retrieve all products listed in the product_details table:*/
use shubham;
show tables;
select * from product_details;

/* Q2
List all unique regions stored in the region table:*/
show tables;
select * from region;
select distinct * from region;


/*Q3
Display all customer details from the customer_details table:*/

select * from customer_details;

/*Q4
Show all sales records from the sales table:*/

select * from sales_details;

/*Q5
Find the total quantity sold for each product:*/

select product_ID ,sum(quantity) from sales_details
group by product_id ;  

/*Q6 
Find the total sales revenue for each customer:*/

show tables;
select * from customer_details;
select * from sales_details;
select customer_name_index, quantity*(unit_price-unit_cost) as divd  from sales_details
group by customer_name_index,divd;



/*Q7
Identify the top 5 products with the highest sales quantity:*/

select  distinct quantity from sales_details;

select * from sales_details;
select * from product_details;
select distinct product_name , quantity from product_details as c
right join sales_details as s
on c.product_id = s.product_id
order by quantity desc;




/*Q8
Calculate the average unit price for each product:*/

select product_name , avg(unit_price) from product_details as c
right join sales_details as s
on c.product_id = s.product_id
group by product_name ;


/*Q9
Retrieve all sales records made through a industries channel:*/

show tables;
select * from sales_details
where channel = "Industries";

/*Q10
Determine the total sales revenue for each country:*/
select * from region;
select * from sales_details;
select country , quantity*(unit_price-unit_cost) as sales_revenue from region as c
right join sales_details as s
on c.region_id = s.region_id;


/*Q11
Find the total sales revenue for each product sold in the 'Electronics' category:*/
select * from sales_details;
select product_name , quantity*(unit_price-unit_cost) as total_sales from product_details as c
right join sales_details as s
on c.product_id = s.product_id;


/*Q12
Identify customers who have made more than 3 orders:*/

select * from sales_details;
select cd.customer_names from customer_details as cd
right outer join sales_details as sd
on cd.customer_names = sd.customer_name_index;
select distinct Order_ID from sales_details;



/*Q13
Retrieve all products with a name containing the word 'Smartphone' and having a unit price greater than $500:*/
select * from product_details as p
left join sales_details as s
on p.product_Id = s.product_Id
where product_name = ("smartphone")
having unit_price >500;


/*Q14
List all countries with total sales revenue exceeding $100,000:*/
select * from region as r
left join sales_details as s
on r.region_Id = s.region_Id
having  quantity*(unit_price-unit_cost)  >10000;
 
/*Q15
Find the average unit price of products sold in cities starting with 'New':*/

select avg(unit_price)  from sales_details as sd
left join region as r
on sd.Region_ID = r.Region_id
where r.City like "new%"
group by Unit_Price;
SELECT * FROM shubham.region
where City like "new%";

 





# Joins Question  Advance

/*Q1
Retrieve all products sold in a specific region:*/
select * from product_details;
select * from region;
select * from sales_details;


select product_Name, city from product_details as p 
right join region as r
on p.product_id = r.region_id
group by product_name,city;



/*Q2
Find the total sales quantity and revenue generated by each product:*/

select product_name ,sum(quantity) from sales_details as s
left join product_details as p
on p.product_id = s.product_id
group by product_name;


/* Q3
List all customers who made purchases in a specific channel:*/
select * from sales_details;
select * from customer_details;
select * from product_details;
select DISTINCT customer_names , channel from customer_details as c
 left join sales_details as s
 on c.customer_id = s.customer_name_index
 group by customer_names , channel;
/*Q4
Calculate the total revenue generated from sales in a specific currency:*/
select * from sales_details;
select currency_code,  quantity*(unit_price-unit_cost) as total_sales from sales_details
group by currency_code , total_sales;

/*Q5 
Retrieve the orders made by a particular customer:*/
select * from sales_details;
select * from customer_details;
select customer_names,order_id from sales_details as s
left join customer_details as c
on c.customer_id = s.customer_name_index
group by customer_names ,order_id;


/*Q6
Retrieve the top 5 best-selling products along with their total revenue:*/
select product_name ,quantity*(unit_price-unit_cost) as revenue from sales_details as s
left join product_details as p
on p.product_id = s.product_id
group by product_name , revenue
order by revenue desc;



/*Q7
Calculate the total revenue generated from sales in each currency, sorted by currency code:*/
select country ,quantity*(unit_price-unit_cost) as total_revenue from sales_details as s
left join region as r
on s.region_id = r.region_id
group by country,total_revenue;



/*Q8
Identify the products with the highest profit margin:*/
select product_name, (unit_price- unit_cost) as profit_margin  from sales_details as s
left join product_details as p 
on p.product_id = s.product_id;
